# Generated by Django 2.2.7 on 2019-11-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='file',
            field=models.FileField(default='upload file', upload_to='uploads/'),
        ),
    ]
