# Generated by Django 2.2.7 on 2019-12-01 12:39

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_model_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=website.models.get_file_path, verbose_name='Website'),
        ),
    ]
